# Generated by Django 2.2.6 on 2020-07-17 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alarmdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='设备激活时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceconf',
            name='device_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='设备同步时间'),
        ),
        migrations.AddField(
            model_name='deviceconf',
            name='update_status',
            field=models.BooleanField(default=0, verbose_name='设备同步状态'),
        ),
        migrations.AddField(
            model_name='deviceconf',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_login_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='设备最后上线时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_logout_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='设备最后下线时间'),
        ),
    ]
