# Generated by Django 2.2.6 on 2020-07-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20200717_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='active_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='设备激活时间'),
        ),
    ]
