# Generated by Django 2.2.6 on 2020-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200717_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='x_index',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='device',
            name='y_index',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='位置'),
        ),
    ]
