# Generated by Django 2.2.6 on 2020-07-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200717_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(default='', max_length=100, verbose_name='设备mac地址'),
        ),
    ]
