# Generated by Django 2.2.6 on 2020-07-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('用户管理', 'user_management'), ('角色管理', 'group_management'))},
        ),
    ]
