# Generated by Django 2.2.6 on 2020-07-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200715_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('user_management', '用户管理'), ('group_management', '角色管理'))},
        ),
    ]
